// This code was generated by a tool.
// Processing tool available at https://github.com/mezoni/binary_generator

library my_package.my_types;

import "package:binary_types/binary_types.dart";

class MyTypes extends BinaryTypes {
  String _header = '''
typedef char CHAR;
typedef struct info {
  int i;
} INFO;
''';    
      
  /**
   *
   */
  MyTypes({DataModel dataModel, BinaryTypes types, Map<String, String> environment}) : super(dataModel: dataModel, types: types) {
    var helper = new BinaryTypeHelper(this);
    helper.declare(_header, environment: environment);  
  }
  
  /**
   * typedef char CHAR
   */
  Int8Type get CHAR => this["CHAR"];
  
  /**
   * typedef struct info INFO
   */
  StructType get INFO => this["INFO"];
  
}

